name: Nathan McBride
description: Certified Magento Developer
meta_description: "Nathan McBride a Bristol Based Magento Developer working at Meanbee in Bath."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.brideo.co.uk'
google_analytics: 'UA-37950107-1'

# Details for the RSS feed generator
url:            'http://www.brideo.co.uk'
author:         'Nathan McBride'
permalink: /:categories/:title
